global:
  scrape_interval:     15s
  external_labels:
    monitor: 'railway-prom'
    env: 'development'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'postgres_metrics_collector'
    scrape_interval: 15s
    scheme: https
    metrics_path: /metrics
    static_configs:
      - targets: ['postgres-metrics-collector-staging.up.railway.app']

  - job_name: 'lucidserum-api'
    scrape_interval: 15s
    metrics_path: /metrics
    scheme: http
    authorization:
      type: Bearer
      credentials_file: /tmp/lucidserum-metrics-token
    static_configs:
      - targets: ['lucidserum-api.railway.internal:3001']
